<?xml version="1.0" encoding="UTF-8"?>
<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/Application2/Project2/bd_crearTickler" name="bd_crearTickler-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/Application2/Project2/bd_crearTickler" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/Application2/Project2/bd_crearTickler" location="../Resources/WSDLs/crearTickler_BD.wsdl"/>
  <binding name="bd_crearTickler_ptt-binding" type="tns:bd_crearTickler_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="bd_crearTickler">
      <soap:operation soapAction="bd_crearTickler"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="bd_crearTickler-service">
    <port name="bd_crearTickler-port" binding="tns:bd_crearTickler_ptt-binding">
      <soap:address location="jca://eis/DB/BSCSPROD"/>
    </port>
  </service>
</definitions>