<wsdl:definitions name="consultarPaqueteDatosSM" targetNamespace="http://www.comcel.com.co/SubscriptionRetrieveSM/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://www.comcel.com.co/SubscriptionRetrieveSM/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<wsdl:types>
		<schema xmlns="http://www.w3.org/2001/XMLSchema">
			<import namespace="http://www.comcel.com.co/SubscriptionRetrieveSM/" schemaLocation="../Schemas/PS_CONSULTAR_PAQUETE_DATOS_SM.xsd"/>
		</schema>
	</wsdl:types>

	<wsdl:message name="Input_Parameters">
		<wsdl:part element="tns:Input_Parameters" name="Input_Parameters"/>
	</wsdl:message>
	<wsdl:message name="WS_Result">
		<wsdl:part element="tns:WS_Result" name="WS_Result"/>
	</wsdl:message>

	<wsdl:portType name="SubscriptionRetrieveSMInterface">
		<wsdl:operation name="consultarPaqueteDatosSM">
			<wsdl:input message="tns:Input_Parameters"/>
			<wsdl:output message="tns:WS_Result"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="SubscriptionRetrieveSMSOAP" type="tns:SubscriptionRetrieveSMInterface">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="consultarPaqueteDatosSM">
			<soap:operation soapAction="http://www.claro.com.co/SubscriptionRetrieveSM/consultarPaqueteDatosSM"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="SubscriptionRetrieveSM">
		<wsdl:port binding="tns:SubscriptionRetrieveSMSOAP" name="SubscriptionRetrieveSMSOAP">
			<soap:address location="http://www.claro.com.co/"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>