<wsdl:definitions name="eliminarPaqueteDatosSM" targetNamespace="http://www.comcel.com.co/EliminarPaqueteSM/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://www.comcel.com.co/EliminarPaqueteSM/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<wsdl:types>
		<schema xmlns="http://www.w3.org/2001/XMLSchema">
			<import namespace="http://www.comcel.com.co/EliminarPaqueteSM/" schemaLocation="../Schemas/PS_ELIMINAR_PAQUETE_DATOS_SM.xsd"/>
		</schema>
	</wsdl:types>

	<wsdl:message name="Input_Parameters">
		<wsdl:part element="tns:Input_Parameters" name="Input_Parameters"/>
	</wsdl:message>
	<wsdl:message name="WS_Result">
		<wsdl:part element="tns:WS_Result" name="WS_Result"/>
	</wsdl:message>

	<wsdl:portType name="EliminarPaqueteSMInterface">
		<wsdl:operation name="eliminarPaqueteDatosSM">
			<wsdl:input message="tns:Input_Parameters"/>
			<wsdl:output message="tns:WS_Result"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="EliminarPaqueteSMSOAP" type="tns:EliminarPaqueteSMInterface">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="eliminarPaqueteDatosSM">
			<soap:operation soapAction="http://www.claro.com.co/EliminarPaqueteSM/eliminarPaqueteDatosSM"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="EliminarPaqueteSM">
		<wsdl:port binding="tns:EliminarPaqueteSMSOAP" name="EliminarPaqueteSMSOAP">
			<soap:address location="http://www.claro.com.co/"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>