<wsdl:definitions name="enviarRecargasSATSM"
	targetNamespace="http://www.comcel.com.co/EnviarRecargasSATSM/"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://www.comcel.com.co/EnviarRecargasSATSM/"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<wsdl:types>
		<schema xmlns="http://www.w3.org/2001/XMLSchema">
			<import namespace="http://www.comcel.com.co/EnviarRecargasSATSM/"
				schemaLocation="../Schemas/PS_ENVIAR_RECARGAS_SAT_SM.xsd" />
		</schema>
	</wsdl:types>

	<wsdl:message name="Input_Parameter">
		<wsdl:part element="tns:Input_Parameter" name="Input_Parameter" />
	</wsdl:message>
	<wsdl:message name="WS_Result">
		<wsdl:part element="tns:WS_Result" name="WS_Result" />
	</wsdl:message>

	<wsdl:portType name="EnviarRecargasSATSMInterface">
		<wsdl:operation name="enviarRecargasSATSM">
			<wsdl:input message="tns:Input_Parameter" />
			<wsdl:output message="tns:WS_Result" />
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="EnviarRecargasSATSMSOAP" type="tns:EnviarRecargasSATSMInterface">
		<soap:binding style="document"
			transport="http://schemas.xmlsoap.org/soap/http" />
		<wsdl:operation name="enviarRecargasSATSM">
			<soap:operation
				soapAction="http://www.claro.com.co/EnviarRecargasSATSM/enviarRecargasSATSM" />
			<wsdl:input>
				<soap:body use="literal" />
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" />
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="EnviarRecargasSATSM">
		<wsdl:port binding="tns:EnviarRecargasSATSMSOAP" name="EnviarRecargasSATSMSOAP">
			<soap:address location="http://www.claro.com.co/" />
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>