<wsdl:definitions name="noCreditAnalysisMatrix"
	targetNamespace="http://www.claro.com.co/rulesEngine/noCreditAnalysisMatrix"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:tns="http://www.claro.com.co/rulesEngine/noCreditAnalysisMatrix"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<wsdl:types>
		<schema xmlns="http://www.w3.org/2001/XMLSchema">
			<import
				namespace="http://www.claro.com.co/rulesEngine/noCreditAnalysisMatrix"
				schemaLocation="../Schemas/PS_NOCREDITANALYSISMATRIX.xsd" />
		</schema>
	</wsdl:types>
	<wsdl:message name="Input_Parameters">
		<wsdl:part element="tns:Input_Parameters" name="Input_Parameters" />
	</wsdl:message>
	<wsdl:message name="WS_Result">
		<wsdl:part element="tns:WS_Result" name="WS_Result" />
	</wsdl:message>
	<wsdl:portType name="NoCreditAnalysisMatrixInterface">
		<wsdl:operation name="noCreditAnalysisMatrix">
			<wsdl:input message="tns:Input_Parameters" />
			<wsdl:output message="tns:WS_Result" />
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="NoCreditAnalysisMatrixSOAP" type="tns:NoCreditAnalysisMatrixInterface">
		<soap:binding style="document"
			transport="http://schemas.xmlsoap.org/soap/http" />
		<wsdl:operation name="noCreditAnalysisMatrix">
			<soap:operation
				soapAction="http://www.claro.com.co/NoCreditAnalysisMatrix/noCreditAnalysisMatrix" />
			<wsdl:input>
				<soap:body use="literal" />
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" />
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="NoCreditAnalysisMatrix">
		<wsdl:port binding="tns:NoCreditAnalysisMatrixSOAP" name="NoCreditAnalysisMatrixSOAP">
			<soap:address location="http://www.claro.com.co/" />
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>