<?xml version="1.0" encoding="UTF-8"?>
<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/Application1/Project1/getClientDocumentStatus" name="getClientDocumentStatus-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/Application1/Project1/getClientDocumentStatus" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/Application1/Project1/getClientDocumentStatus" location="../Resources/WSDLs/getClientDocumentStatus_BD.wsdl"/>
  <binding name="getClientDocumentStatus_ptt-binding" type="tns:getClientDocumentStatus_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="getClientDocumentStatus">
      <soap:operation soapAction="getClientDocumentStatus"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="getClientDocumentStatus-service">
    <port name="getClientDocumentStatus-port" binding="tns:getClientDocumentStatus_ptt-binding">
      <soap:address location="jca://eis/DB/Activa"/>
    </port>
  </service>
</definitions>