<?xml version="1.0" encoding="UTF-8"?>
<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/insertInternalInfoCredit" name="bd_insertInternalCreditInformation-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/sp/insertInternalInfoCredit" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/insertInternalInfoCredit" location="../Resources/WSDLs/insertInternalCreditInformation_BD.wsdl"/>
  <binding name="bd_insertInternalCreditInformation_ptt-binding" type="tns:bd_insertInternalCreditInformation_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="bd_insertInternalCreditInformation">
      <soap:operation soapAction="bd_insertInternalCreditInformation"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="bd_insertInternalCreditInformation-service">
    <port name="bd_insertInternalCreditInformation-port" binding="tns:bd_insertInternalCreditInformation_ptt-binding">
      <soap:address location="jca://eis/DB/Activa"/>
    </port>
  </service>
</definitions>