<?xml version="1.0" encoding="UTF-8"?>
<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/Application2/Project2/bd_updateCreditScore" name="bd_updateCreditScore-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/Application2/Project2/bd_updateCreditScore" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/Application2/Project2/bd_updateCreditScore" location="../Resources/WSDLs/updateCreditScore_BD.wsdl"/>
  <binding name="bd_updateCreditScore_ptt-binding" type="tns:bd_updateCreditScore_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="bd_updateCreditScore">
      <soap:operation soapAction="bd_updateCreditScore"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="bd_updateCreditScore-service">
    <port name="bd_updateCreditScore-port" binding="tns:bd_updateCreditScore_ptt-binding">
      <soap:address location="jca://eis/DB/Activa"/>
    </port>
  </service>
</definitions>