<wsdl:definitions name="CalcularProvisionTrama401" targetNamespace="http://www.comcel.com.co/CalcularProvisionTrama401/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://www.comcel.com.co/CalcularProvisionTrama401/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<wsdl:types>
			<schema xmlns="http://www.w3.org/2001/XMLSchema">
				<import namespace="http://www.comcel.com.co/CalcularProvisionTrama401/" schemaLocation="../Schemas/PS_ITEL_CALCULARPROVISIONTRAMA401.xsd"/>
			</schema>
	</wsdl:types>
	<wsdl:message name="Input_Parameters">
		<wsdl:part element="tns:Input_Parameters" name="Input_Parameters"/>
	</wsdl:message>
	<wsdl:message name="WS_Result">
		<wsdl:part element="tns:WS_Result" name="WS_Result"/>
	</wsdl:message>
	<wsdl:portType name="CalcularProvisionTrama401">
		<wsdl:operation name="calcularProvisionTrama401">
			<wsdl:input message="tns:Input_Parameters"/>
			<wsdl:output message="tns:WS_Result"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="CalcularProvisionTrama401SOAP" type="tns:CalcularProvisionTrama401">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="calcularProvisionTrama401">
			<soap:operation soapAction="http://www.comcel.com.co/CalcularProvisionTrama401/calcularProvisionTrama401"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="CalcularProvisionTrama401">
		<wsdl:port binding="tns:CalcularProvisionTrama401SOAP" name="CalcularProvisionTrama401SOAP">
			<soap:address location="http://www.comcel.com.co/"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>