<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/ITEL/Consultas/consultarTarifasPrepago" name="consultarTarifasPrepago-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/ITEL/Consultas/consultarTarifasPrepago" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ITEL/Consultas/consultarTarifasPrepago" location="../Resources/WSDLs/consultarTarifasPrepago.wsdl"/>
  <binding name="consultarTarifasPrepago_ptt-binding" type="tns:consultarTarifasPrepago_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="consultarTarifasPrepago">
      <soap:operation soapAction="consultarTarifasPrepago"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="consultarTarifasPrepago-service">
    <port name="consultarTarifasPrepago-port" binding="tns:consultarTarifasPrepago_ptt-binding">
      <soap:address location="jca://eis/DB/SOADES"/>
    </port>
  </service>
</definitions>