<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/jms/Comcel/ITEL/enviarAuditoriaRecargaSATJMS" name="enviarAuditoriaRecargaSATJMS-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/jms/Comcel/ITEL/enviarAuditoriaRecargaSATJMS" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/jms/Comcel/ITEL/enviarAuditoriaRecargaSATJMS" location="../Resources/WSDLs/enviarAuditoriaRecargaSATJMS.wsdl"/>
  <binding name="enviarAuditoriaRecargaSAT_ptt-binding" type="tns:enviarAuditoriaRecargaSAT_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="enviarAuditoriaRecargaSAT">
      <soap:operation soapAction="enviarAuditoriaRecargaSAT"/>
      <input>
        <soap:body use="literal"/>
      </input>
    </operation>
  </binding>
  <service name="enviarAuditoriaRecargaSATJMS-service">
    <port name="enviarAuditoriaRecargaSATJMS-port" binding="tns:enviarAuditoriaRecargaSAT_ptt-binding">
      <soap:address location="jca://eis/wls/Queue"/>
    </port>
  </service>
</definitions>