<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/jms/Comcel/ITEL/enviarAuditoriaDiaSorpresaElegidosJMS" name="enviarAuditoriaDiaSorpresaElegidosJMS-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/jms/Comcel/ITEL/enviarAuditoriaDiaSorpresaElegidosJMS" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/jms/Comcel/ITEL/enviarAuditoriaDiaSorpresaElegidosJMS" location="../Resources/WSDLs/enviarAuditoriaDiaSorpresaElegidosJMS.wsdl"/>
  <binding name="enviarAuditoriaDiaSorpresaElegidos_ptt-binding" type="tns:enviarAuditoriaDiaSorpresaElegidos_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="enviarAuditoriaDiaSorpresaElegidos">
      <soap:operation soapAction="enviarAuditoriaDiaSorpresaElegidos"/>
      <input>
        <soap:body use="literal"/>
      </input>
    </operation>
  </binding>
  <service name="enviarAuditoriaDiaSorpresaElegidosJMS-service">
    <port name="enviarAuditoriaDiaSorpresaElegidosJMS-port" binding="tns:enviarAuditoriaDiaSorpresaElegidos_ptt-binding">
      <soap:address location="jca://eis/wls/Queue"/>
    </port>
  </service>
</definitions>