<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/jms/Comcel/ITEL/enviarAuditoriaRecargaDatosJMS" name="enviarAuditoriaRecargaDatosJMS-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/jms/Comcel/ITEL/enviarAuditoriaRecargaDatosJMS" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/jms/Comcel/ITEL/enviarAuditoriaRecargaDatosJMS" location="../Resources/WSDLs/enviarAuditoriaRecargaDatosJMS.wsdl"/>
  <binding name="enviarAuditoriaRecargaDatos_ptt-binding" type="tns:enviarAuditoriaRecargaDatos_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="enviarAuditoriaRecargaDatos">
      <soap:operation soapAction="enviarAuditoriaRecargaDatos"/>
      <input>
        <soap:body use="literal"/>
      </input>
    </operation>
  </binding>
  <service name="enviarAuditoriaRecargaDatosJMS-service">
    <port name="enviarAuditoriaRecargaDatosJMS-port" binding="tns:enviarAuditoriaRecargaDatos_ptt-binding">
      <soap:address location="jca://eis/wls/Queue"/>
    </port>
  </service>
</definitions>