<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/jms/Comcel/ITEL/enviarAuditoriaRecargaRARJMS" name="enviarAuditoriaRecargaRARJMS-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/jms/Comcel/ITEL/enviarAuditoriaRecargaRARJMS" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/jms/Comcel/ITEL/enviarAuditoriaRecargaRARJMS" location="../Resources/WSDLs/enviarAuditoriaRecargaRARJMS.wsdl"/>
  <binding name="enviarAuditoriaRecargaRAR_ptt-binding" type="tns:enviarAuditoriaRecargaRAR_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="enviarAuditoriaRecargaRAR">
      <soap:operation soapAction="enviarAuditoriaRecargaRAR"/>
      <input>
        <soap:body use="literal"/>
      </input>
    </operation>
  </binding>
  <service name="enviarAuditoriaRecargaRARJMS-service">
    <port name="enviarAuditoriaRecargaRARJMS-port" binding="tns:enviarAuditoriaRecargaRAR_ptt-binding">
      <soap:address location="jca://eis/wls/Queue"/>
    </port>
  </service>
</definitions>