<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/jms/Comcel/ITEL/enviarAuditoriaPromoJMS" name="enviarAuditoriaPromoJMS-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/jms/Comcel/ITEL/enviarAuditoriaPromoJMS" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/jms/Comcel/ITEL/enviarAuditoriaPromoJMS" location="../Resources/WSDLs/enviarAuditoriaPromoJMS.wsdl"/>
  <binding name="enviarAuditoriaPromo_ptt-binding" type="tns:enviarAuditoriaPromo_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="enviarAuditoriaPromo">
      <soap:operation soapAction="enviarAuditoriaPromo"/>
      <input>
        <soap:body use="literal"/>
      </input>
    </operation>
  </binding>
  <service name="enviarAuditoriaPromoJMS-service">
    <port name="enviarAuditoriaPromoJMS-port" binding="tns:enviarAuditoriaPromo_ptt-binding">
      <soap:address location="jca://eis/wls/Queue"/>
    </port>
  </service>
</definitions>