<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/jms/Comcel/ITEL/enviarAuditoriaDiaSorpresaRecargaJMS" name="enviarAuditoriaDiaSorpresaRecargaJMS-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/jms/Comcel/ITEL/enviarAuditoriaDiaSorpresaRecargaJMS" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/jms/Comcel/ITEL/enviarAuditoriaDiaSorpresaRecargaJMS" location="../Resources/WSDLs/enviarAuditoriaDiaSorpresaRecargaJMS.wsdl"/>
  <binding name="enviarAuditoriaDiaSorpresaRecarga_ptt-binding" type="tns:enviarAuditoriaDiaSorpresaRecarga_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="enviarAuditoriaDiaSorpresaRecarga">
      <soap:operation soapAction="enviarAuditoriaDiaSorpresaRecarga"/>
      <input>
        <soap:body use="literal"/>
      </input>
    </operation>
  </binding>
  <service name="enviarAuditoriaDiaSorpresaRecargaJMS-service">
    <port name="enviarAuditoriaDiaSorpresaRecargaJMS-port" binding="tns:enviarAuditoriaDiaSorpresaRecarga_ptt-binding">
      <soap:address location="jca://eis/wls/Queue"/>
    </port>
  </service>
</definitions>