<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/jms/Comcel/ITEL/enviarAuditoriaPromoPaquetesTATJMS" name="enviarAuditoriaPromoPaquetesTATJMS-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/jms/Comcel/ITEL/enviarAuditoriaPromoPaquetesTATJMS" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/jms/Comcel/ITEL/enviarAuditoriaPromoPaquetesTATJMS" location="../Resources/WSDLs/enviarAuditoriaPromoPaquetesTATJMS.wsdl"/>
  <binding name="enviarAuditoriaPromoPaquetesTAT_ptt-binding" type="tns:enviarAuditoriaPromoPaquetesTAT_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="enviarAuditoriaPromoPaquetesTAT">
      <soap:operation soapAction="enviarAuditoriaPromoPaquetesTAT"/>
      <input>
        <soap:body use="literal"/>
      </input>
    </operation>
  </binding>
  <service name="enviarAuditoriaPromoPaquetesTATJMS-service">
    <port name="enviarAuditoriaPromoPaquetesTATJMS-port" binding="tns:enviarAuditoriaPromoPaquetesTAT_ptt-binding">
      <soap:address location="jca://eis/wls/Queue"/>
    </port>
  </service>
</definitions>