<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/jms/Comcel/ITEL/enviarAuditoriaBAMJMS" name="enviarAuditoriaBAMJMS-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/jms/Comcel/ITEL/enviarAuditoriaBAMJMS" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/jms/Comcel/ITEL/enviarAuditoriaBAMJMS" location="../Resources/WSDLs/enviarAuditoriaBAMJMS.wsdl"/>
  <binding name="enviarAuditoriaBAM_ptt-binding" type="tns:enviarAuditoriaBAM_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="enviarAuditoriaBAM">
      <soap:operation soapAction="enviarAuditoriaBAM"/>
      <input>
        <soap:body use="literal"/>
      </input>
    </operation>
  </binding>
  <service name="enviarAuditoriaBAMJMS-service">
    <port name="enviarAuditoriaBAMJMS-port" binding="tns:enviarAuditoriaBAM_ptt-binding">
      <soap:address location="jca://eis/wls/Queue"/>
    </port>
  </service>
</definitions>