<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/ITELSOA/Reglas/bd_insertarAuditoriaCambioPlan" name="bd_insertarAuditoriaCambioPlan-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/ITELSOA/Reglas/bd_insertarAuditoriaCambioPlan" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ITELSOA/Reglas/bd_insertarAuditoriaCambioPlan" location="../Resources/WSDLs/insertarAuditoriaCambioPlan_BD.wsdl"/>
  <binding name="bd_insertarAuditoriaCambioPlan_ptt-binding" type="tns:bd_insertarAuditoriaCambioPlan_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="bd_insertarAuditoriaCambioPlan">
      <soap:operation soapAction="bd_insertarAuditoriaCambioPlan"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="bd_insertarAuditoriaCambioPlan-service">
    <port name="bd_insertarAuditoriaCambioPlan-port" binding="tns:bd_insertarAuditoriaCambioPlan_ptt-binding">
      <soap:address location="jca://eis/DB/ITEL_SOA"/>
    </port>
  </service>
</definitions>