<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/ITELSOA/Reglas/bd_insertarAuditoriaCrearSuscriptor" name="bd_insertarAuditoriaCrearSuscriptor-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/ITELSOA/Reglas/bd_insertarAuditoriaCrearSuscriptor" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ITELSOA/Reglas/bd_insertarAuditoriaCrearSuscriptor" location="../Resources/WSDLs/insertarAuditoriaCrearSuscriptor_BD.wsdl"/>
  <binding name="bd_insertarAuditoriaCrearSuscriptor_ptt-binding" type="tns:bd_insertarAuditoriaCrearSuscriptor_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="bd_insertarAuditoriaCrearSuscriptor">
      <soap:operation soapAction="bd_insertarAuditoriaCrearSuscriptor"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="bd_insertarAuditoriaCrearSuscriptor-service">
    <port name="bd_insertarAuditoriaCrearSuscriptor-port" binding="tns:bd_insertarAuditoriaCrearSuscriptor_ptt-binding">
      <soap:address location="jca://eis/DB/ITEL_SOA"/>
    </port>
  </service>
</definitions>