<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/Ensayo/Reglas/bd_insertarAuditoriaSegundoElegido" name="bd_insertarAuditoriaSegundoElegido-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/Ensayo/Reglas/bd_insertarAuditoriaSegundoElegido" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/Ensayo/Reglas/bd_insertarAuditoriaSegundoElegido" location="../Resources/WSDLs/insertarAuditoriaSegundoElegido_BD.wsdl"/>
  <binding name="bd_insertarAuditoriaSegundoElegido_ptt-binding" type="tns:bd_insertarAuditoriaSegundoElegido_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="bd_insertarAuditoriaSegundoElegido">
      <soap:operation soapAction="bd_insertarAuditoriaSegundoElegido"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="bd_insertarAuditoriaSegundoElegido-service">
    <port name="bd_insertarAuditoriaSegundoElegido-port" binding="tns:bd_insertarAuditoriaSegundoElegido_ptt-binding">
      <soap:address location="jca://eis/DB/ITEL_SOA"/>
    </port>
  </service>
</definitions>