<wsdl:definitions name="ContratoCadenaEntradaSalida" targetNamespace="http://www.example.org/ContratoCadenaEntradaSalida/" xmlns:tns="http://www.example.org/ContratoCadenaEntradaSalida/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd1="http://www.example.org/FirmaCadenaEntradaSalida">
    <wsdl:types>
    	<xsd:schema>
    		<xsd:import namespace="http://www.example.org/FirmaCadenaEntradaSalida" schemaLocation="../../Firmas_XSD/CadenaEntradaSalida/FirmaCadenaEntradaSalida.xsd">
    		</xsd:import></xsd:schema></wsdl:types>
    <wsdl:message name="miOperacionRequest">
    	<wsdl:part name="parameters" element="xsd1:CadenaEntradaSalidaRequest">
    	</wsdl:part>
    </wsdl:message>
    <wsdl:message name="miOperacionResponse">
    	<wsdl:part name="parameters" element="xsd1:CadenaEntradaSalidaResponse">
    	</wsdl:part>
    </wsdl:message>
    <wsdl:portType name="miTipoPuerto">
    	<wsdl:operation name="miOperacion">
    		<wsdl:input message="tns:miOperacionRequest"/>
    		<wsdl:output message="tns:miOperacionResponse"/>
    	</wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="miBinding" type="tns:miTipoPuerto">
    	<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    	<wsdl:operation name="miOperacion">
    		<soap:operation soapAction="http://www.example.org/ContratoCadenaEntradaSalida/miOperacion"/>
    		<wsdl:input>
    			<soap:body use="literal"/>
    		</wsdl:input>
    		<wsdl:output>
    			<soap:body use="literal"/>
    		</wsdl:output>
    	</wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="MiServicio">
		<wsdl:port name="miPuerto" binding="tns:miBinding">
			<soap:address location="http://www.example.org/"/>
		</wsdl:port>
	</wsdl:service></wsdl:definitions>