<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/Application1/Project1/insertarEnviaPort" name="insertarEnviaPort-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/Application1/Project1/insertarEnviaPort" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/Application1/Project1/insertarEnviaPort" location="../Resources/WSDLs/insertarEnviaPort.wsdl"/>
  <binding name="insertarEnviaPort_ptt-binding" type="tns:insertarEnviaPort_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="insertarEnviaPort">
      <soap:operation soapAction="insertarEnviaPort"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="insertarEnviaPort-service">
    <port name="insertarEnviaPort-port" binding="tns:insertarEnviaPort_ptt-binding">
      <soap:address location="jca://eis/DB/SMOQA"/>
    </port>
  </service>
</definitions>