<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/SOA/Adapters/bd_auditExecution" name="bd_auditExecution-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/SOA/Adapters/bd_auditExecution" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/SOA/Adapters/bd_auditExecution" location="../Resources/WSDLs/auditExecution_BD.wsdl"/>
  <binding name="bd_auditExecution_ptt-binding" type="tns:bd_auditExecution_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="bd_auditExecution">
      <soap:operation soapAction="bd_auditExecution"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="bd_auditExecution-service">
    <port name="bd_auditExecution-port" binding="tns:bd_auditExecution_ptt-binding">
      <soap:address location="jca://eis/DB/Rules_Engine"/>
    </port>
  </service>
</definitions>