<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="BPEL_Reglas_Negocio01"
     targetNamespace="http://xmlns.oracle.com/Application_OSB_REGLASNEGOCIO_FORM_TRANSPORTE01/Project_OSB_REGLASNEGOCIO_FORM_TRANSPORTE01/BPEL_Reglas_Negocio01"
     xmlns:ns1="http://www.example.org/FirmaFormRegistroAutomotor"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:client="http://xmlns.oracle.com/Application_OSB_REGLASNEGOCIO_FORM_TRANSPORTE01/Project_OSB_REGLASNEGOCIO_FORM_TRANSPORTE01/BPEL_Reglas_Negocio01"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <plnk:partnerLinkType name="BPEL_Reglas_Negocio01">
        <plnk:role name="BPEL_Reglas_Negocio01Provider" portType="client:BPEL_Reglas_Negocio01"/>
    </plnk:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:ns1="http://www.example.org/FirmaFormRegistroAutomotor"
             xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:client="http://xmlns.oracle.com/Application_OSB_REGLASNEGOCIO_FORM_TRANSPORTE01/Project_OSB_REGLASNEGOCIO_FORM_TRANSPORTE01/BPEL_Reglas_Negocio01"
             xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
            <import namespace="http://www.example.org/FirmaFormRegistroAutomotor" schemaLocation="xsd/FirmaFormRegistroAutomotor.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="BPEL_Reglas_Negocio01RequestMessage">
        <wsdl:part name="payload" element="ns1:formularioEntrada"/>
    </wsdl:message>
    <wsdl:message name="BPEL_Reglas_Negocio01ResponseMessage">
        <wsdl:part name="payload" element="ns1:formularioRetorno"/>
    </wsdl:message>
    <wsdl:portType name="BPEL_Reglas_Negocio01">
        <wsdl:operation name="process">
            <wsdl:input message="client:BPEL_Reglas_Negocio01RequestMessage"/>
            <wsdl:output message="client:BPEL_Reglas_Negocio01ResponseMessage"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
