<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/Application_PCO_FIRMACONTRATO_PA03/Project_PCO_FIRMACONTRATO_PA03/BSReferenceLocaciones" name="BSReferenceLocaciones-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="BSReferenceLocaciones.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/Application_PCO_FIRMACONTRATO_PA03/Project_PCO_FIRMACONTRATO_PA03/BSReferenceLocaciones"/>
    <wsdl:binding name="BSReferenceLocaciones_ptt-binding" type="bsr:BSReferenceLocaciones_ptt" xmlns:bsr="http://xmlns.oracle.com/pcbpel/adapter/db/Application_PCO_FIRMACONTRATO_PA03/Project_PCO_FIRMACONTRATO_PA03/BSReferenceLocaciones">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="BSReferenceLocaciones">
            <soap:operation soapAction="BSReferenceLocaciones"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>