<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/ITEL/Adaptadores/bd_actualizarCambiosDePlan" name="bd_actualizarCambiosDePlan-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/ITEL/Adaptadores/bd_actualizarCambiosDePlan" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ITEL/Adaptadores/bd_actualizarCambiosDePlan" location="../Proxies/actualizarCambiosDePlan_BD.wsdl"/>
  <binding name="bd_actualizarCambiosDePlan_ptt-binding" type="tns:bd_actualizarCambiosDePlan_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="bd_actualizarCambiosDePlan">
      <soap:operation soapAction="bd_actualizarCambiosDePlan"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="bd_actualizarCambiosDePlan-service">
    <port name="bd_actualizarCambiosDePlan-port" binding="tns:bd_actualizarCambiosDePlan_ptt-binding">
      <soap:address location="jca://eis/DB/SOA_DEV_LOCAL"/>
    </port>
  </service>
</definitions>