<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/ITEL/Adaptadores/bd_actualizarMinElegidos" name="bd_actualizarMinElegidos-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/ITEL/Adaptadores/bd_actualizarMinElegidos" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ITEL/Adaptadores/bd_actualizarMinElegidos" location="../Resources/WSDLs/actualizarMinElegidos_BD.wsdl"/>
  <binding name="bd_actualizarMinElegidos_ptt-binding" type="tns:bd_actualizarMinElegidos_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="bd_actualizarMinElegidos">
      <soap:operation soapAction="bd_actualizarMinElegidos"/>
      <input>
        <soap:body use="literal"/>
      </input>
    </operation>
  </binding>
  <service name="bd_actualizarMinElegidos-service">
    <port name="bd_actualizarMinElegidos-port" binding="tns:bd_actualizarMinElegidos_ptt-binding">
      <soap:address location="jca://eis/DB/ITEL_SOA"/>
    </port>
  </service>
</definitions>