<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/ITEL/Adaptadores/db_consultarPlanesOCS" name="db_consultarPlanesOCS-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/ITEL/Adaptadores/db_consultarPlanesOCS" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ITEL/Adaptadores/db_consultarPlanesOCS" location="../Resources/WSDLs/consultarPlanesOCS.wsdl"/>
  <binding name="db_consultarPlanesOCS_ptt-binding" type="tns:db_consultarPlanesOCS_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="db_consultarPlanesOCS">
      <soap:operation soapAction="db_consultarPlanesOCS"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="db_consultarPlanesOCS-service">
    <port name="db_consultarPlanesOCS-port" binding="tns:db_consultarPlanesOCS_ptt-binding">
      <soap:address location="jca://eis/DB/ITEL_SOA"/>
    </port>
  </service>
</definitions>