<?xml version="1.0" encoding="UTF-8"?>
<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/Application2/Project2/bd_consultarMinOcsDrp" name="bd_consultarMinOcsDrp-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/Application2/Project2/bd_consultarMinOcsDrp" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/Application2/Project2/bd_consultarMinOcsDrp" location="../Resources/WSDLs/consultarMinOcsDrp_BD.wsdl"/>
  <binding name="bd_consultarMinOcsDrp_ptt-binding" type="tns:bd_consultarMinOcsDrp_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="bd_consultarMinOcsDrp">
      <soap:operation soapAction="bd_consultarMinOcsDrp"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="bd_consultarMinOcsDrp-service">
    <port name="bd_consultarMinOcsDrp-port" binding="tns:bd_consultarMinOcsDrp_ptt-binding">
      <soap:address location="jca://eis/DB/ITEL_SOA"/>
    </port>
  </service>
</definitions>