<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/ITEL/Adaptadores/bd_consultarRangoRecargaOCS" name="bd_consultarRangoRecargaOCS-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/ITEL/Adaptadores/bd_consultarRangoRecargaOCS" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ITEL/Adaptadores/bd_consultarRangoRecargaOCS" location="../Resources/WSDLs/consultarRangoRecargaOCS_BD.wsdl"/>
  <binding name="bd_consultarRangoRecargaOCS_ptt-binding" type="tns:bd_consultarRangoRecargaOCS_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="bd_consultarRangoRecargaOCS">
      <soap:operation soapAction="bd_consultarRangoRecargaOCS"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="bd_consultarRangoRecargaOCS-service">
    <port name="bd_consultarRangoRecargaOCS-port" binding="tns:bd_consultarRangoRecargaOCS_ptt-binding">
      <soap:address location="jca://eis/DB/ITEL_SOA"/>
    </port>
  </service>
</definitions>