<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/Ensayo/Reglas/bd_consultarFAFIDVigencia" name="bd_consultarFAFIDVigencia-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/Ensayo/Reglas/bd_consultarFAFIDVigencia" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/Ensayo/Reglas/bd_consultarFAFIDVigencia" location="../Resources/WSDLs/consultarFAFIDVigencia_BD.wsdl"/>
  <binding name="bd_consultarFAFIDVigencia_ptt-binding" type="tns:bd_consultarFAFIDVigencia_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="bd_consultarFAFIDVigencia">
      <soap:operation soapAction="bd_consultarFAFIDVigencia"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="bd_consultarFAFIDVigencia-service">
    <port name="bd_consultarFAFIDVigencia-port" binding="tns:bd_consultarFAFIDVigencia_ptt-binding">
      <soap:address location="jca://eis/DB/ITEL_SOA"/>
    </port>
  </service>
</definitions>