<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/Ensayo/Reglas/bd_consultarVigenciaElegido" name="bd_consultarVigenciaElegido-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/Ensayo/Reglas/bd_consultarVigenciaElegido" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/Ensayo/Reglas/bd_consultarVigenciaElegido" location="../Resources/WSDLs/consultarVigenciaElegido_BD.wsdl"/>
  <binding name="bd_consultarVigenciaElegido_ptt-binding" type="tns:bd_consultarVigenciaElegido_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="bd_consultarVigenciaElegido">
      <soap:operation soapAction="bd_consultarVigenciaElegido"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="bd_consultarVigenciaElegido-service">
    <port name="bd_consultarVigenciaElegido-port" binding="tns:bd_consultarVigenciaElegido_ptt-binding">
      <soap:address location="jca://eis/DB/ITELDB"/>
    </port>
  </service>
</definitions>