<definitions
	targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/ITEL/Adaptadores/consultarCambiosFNF"
	name="consultarCambiosFNF-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/"
	xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/ITEL/Adaptadores/consultarCambiosFNF"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
	<import
		namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ITEL/Adaptadores/consultarCambiosFNF"
		location="../Resources/WSDLs/consultarCambiosFNF_BD.wsdl" />
	<binding name="consultarCambiosFNF_ptt-binding" type="tns:consultarCambiosFNF_ptt">
		<soap:binding style="document"
			transport="http://www.bea.com/wli/sb/transports/jca" />
		<operation name="consultarCambiosFNF">
			<soap:operation soapAction="consultarCambiosFNF" />
			<input>
				<soap:body use="literal" />
			</input>
			<output>
				<soap:body use="literal" />
			</output>
		</operation>
	</binding>
	<service name="consultarCambiosFNF-service">
		<port name="consultarCambiosFNF-port" binding="tns:consultarCambiosFNF_ptt-binding">
			<soap:address location="jca://eis/DB/ITEL_SOA_CENT" />
		</port>
	</service>
</definitions>