<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/ITEL/Adaptadores/bd_consultarPaquetesAdd" name="bd_consultarPaquetesAdd-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/ITEL/Adaptadores/bd_consultarPaquetesAdd" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ITEL/Adaptadores/bd_consultarPaquetesAdd" location="../Resources/WSDLs/consultarPaquetesAddBB_BD.wsdl"/>
  <binding name="bd_consultarPaquetesAdd_ptt-binding" type="tns:bd_consultarPaquetesAdd_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="bd_consultarPaquetesAdd">
      <soap:operation soapAction="bd_consultarPaquetesAdd"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="bd_consultarPaquetesAdd-service">
    <port name="bd_consultarPaquetesAdd-port" binding="tns:bd_consultarPaquetesAdd_ptt-binding">
      <soap:address location="jca://eis/DB/ITEL_SOA_CENT"/>
    </port>
  </service>
</definitions>