<?xml version="1.0" encoding="UTF-8"?>
<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/ITEL/Adaptadores/bd_consultarParametrosBB" name="bd_consultarParametrosBB-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/ITEL/Adaptadores/bd_consultarParametrosBB" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ITEL/Adaptadores/bd_consultarParametrosBB" location="../Resources/WSDLs/consultarParametrosBB_BD.wsdl"/>
  <binding name="bd_consultarParametrosBB_ptt-binding" type="tns:bd_consultarParametrosBB_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="bd_consultarParametrosBB">
      <soap:operation soapAction="bd_consultarParametrosBB"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="bd_consultarParametrosBB-service">
    <port name="bd_consultarParametrosBB-port" binding="tns:bd_consultarParametrosBB_ptt-binding">
      <soap:address location="jca://eis/DB/ITEL_SOA_CENT"/>
    </port>
  </service>
</definitions>