<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/ITEL/Adaptadores/bd_consultarRangoSDP" name="bd_consultarRangoSDP-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/ITEL/Adaptadores/bd_consultarRangoSDP" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ITEL/Adaptadores/bd_consultarRangoSDP" location="../Resources/WSDLs/consultarRangoSDP_BD.wsdl"/>
  <binding name="bd_consultarRangoSDP_ptt-binding" type="tns:bd_consultarRangoSDP_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="bd_consultarRangoSDP">
      <soap:operation soapAction="bd_consultarRangoSDP"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="bd_consultarRangoSDP-service">
    <port name="bd_consultarRangoSDP-port" binding="tns:bd_consultarRangoSDP_ptt-binding">
      <soap:address location="jca://eis/DB/ITEL_SOA"/>
    </port>
  </service>
</definitions>