<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/Application2/Project2/bd_consultarOfferAmdocs" name="bd_consultarOfferAmdocs-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/Application2/Project2/bd_consultarOfferAmdocs" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/Application2/Project2/bd_consultarOfferAmdocs" location="../Resources/WSDLs/consultarOfferAmdocs_BD.wsdl"/>
  <binding name="bd_consultarOfferAmdocs_ptt-binding" type="tns:bd_consultarOfferAmdocs_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="bd_consultarOfferAmdocs">
      <soap:operation soapAction="bd_consultarOfferAmdocs"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="bd_consultarOfferAmdocs-service">
    <port name="bd_consultarOfferAmdocs-port" binding="tns:bd_consultarOfferAmdocs_ptt-binding">
      <soap:address location="jca://eis/DB/ITEL_SOA"/>
    </port>
  </service>
</definitions>