<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/ITEL/Adaptadores/bd_consultarMercadeoAMOCS" name="bd_consultarMercadeoAMOCS-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/ITEL/Adaptadores/bd_consultarMercadeoAMOCS" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ITEL/Adaptadores/bd_consultarMercadeoAMOCS" location="../Resources/WSDLs/consultarMercadeoAMOCS_BD.wsdl"/>
  <binding name="bd_consultarMercadeoAMOCS_ptt-binding" type="tns:bd_consultarMercadeoAMOCS_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="bd_consultarMercadeoAMOCS">
      <soap:operation soapAction="bd_consultarMercadeoAMOCS"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="bd_consultarMercadeoAMOCS-service">
    <port name="bd_consultarMercadeoAMOCS-port" binding="tns:bd_consultarMercadeoAMOCS_ptt-binding">
      <soap:address location="jca://eis/DB/ITEL_SOA"/>
    </port>
  </service>
</definitions>