<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/ITEL/Adaptadores/bd_consultarVigenciaElegidoSMS_db" name="bd_consultarVigenciaElegidoSMS_db-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/ITEL/Adaptadores/bd_consultarVigenciaElegidoSMS_db" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ITEL/Adaptadores/bd_consultarVigenciaElegidoSMS_db" location="../Resources/WSDLs/consultarVigenciaElegidoSMS_BD.wsdl"/>
  <binding name="bd_consultarVigenciaElegidoSMS_db_ptt-binding" type="tns:bd_consultarVigenciaElegidoSMS_db_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="bd_consultarVigenciaElegidoSMS_db">
      <soap:operation soapAction="bd_consultarVigenciaElegidoSMS_db"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="bd_consultarVigenciaElegidoSMS_db-service">
    <port name="bd_consultarVigenciaElegidoSMS_db-port" binding="tns:bd_consultarVigenciaElegidoSMS_db_ptt-binding">
      <soap:address location="jca://eis/DB/ITEL_SOA"/>
    </port>
  </service>
</definitions>