<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/jms/Comcel/ITEL/enviarNotificacionSMSJMS" name="enviarNotificacionSMSJMS-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/jms/Comcel/ITEL/enviarNotificacionSMSJMS" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/jms/Comcel/ITEL/enviarNotificacionSMSJMS" location="../Resources/WSDLs/enviarNotificacionSMSJMS.wsdl"/>
  <binding name="enviarNotificacionSMS_ptt-binding" type="tns:enviarNotificacionSMS_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="enviarNotificacionSMS">
      <soap:operation soapAction="enviarNotificacionSMS"/>
      <input>
        <soap:body use="literal"/>
      </input>
    </operation>
  </binding>
  <service name="enviarNotificacionSMSJMS-service">
    <port name="enviarNotificacionSMSJMS-port" binding="tns:enviarNotificacionSMS_ptt-binding">
      <soap:address location="jca://eis/wls/Queue"/>
    </port>
  </service>
</definitions>