<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/jms/Comcel/ITEL/enviarAuditoriaJMS" name="enviarAuditoriaJMS-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/jms/Comcel/ITEL/enviarAuditoriaJMS" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/jms/Comcel/ITEL/enviarAuditoriaJMS" location="../Resources/WSDLs/enviarAuditoriaJMS.wsdl"/>
  <binding name="enviarAuditoria_ptt-binding" type="tns:enviarAuditoria_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="enviarAuditoria">
      <soap:operation soapAction="enviarAuditoria"/>
      <input>
        <soap:body use="literal"/>
      </input>
    </operation>
  </binding>
  <service name="enviarAuditoriaJMS-service">
    <port name="enviarAuditoriaJMS-port" binding="tns:enviarAuditoria_ptt-binding">
      <soap:address location="jca://eis/wls/Queue"/>
    </port>
  </service>
</definitions>