<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/ITEL/Adaptadores/bd_insertarAuditoriaRecargaDatos" name="bd_insertarAuditoriaRecargaDatos-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/ITEL/Adaptadores/bd_insertarAuditoriaRecargaDatos" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ITEL/Adaptadores/bd_insertarAuditoriaRecargaDatos" location="../Resources/WSDLs/insertarAuditoriaRecargaDatos_BD.wsdl"/>
  <binding name="bd_insertarAuditoriaRecargaDatos_ptt-binding" type="tns:bd_insertarAuditoriaRecargaDatos_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="bd_insertarAuditoriaRecargaDatos">
      <soap:operation soapAction="bd_insertarAuditoriaRecargaDatos"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="bd_insertarAuditoriaRecargaDatos-service">
    <port name="bd_insertarAuditoriaRecargaDatos-port" binding="tns:bd_insertarAuditoriaRecargaDatos_ptt-binding">
      <soap:address location="jca://eis/DB/ITEL_SOA"/>
    </port>
  </service>
</definitions>