<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/ITEL/Adaptadores/bd_insertarCantidadConsultas" name="bd_insertarCantidadConsultas-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/ITEL/Adaptadores/bd_insertarCantidadConsultas" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ITEL/Adaptadores/bd_insertarCantidadConsultas" location="../Resources/WSDLs/insertarCantidadConsultas_BD.wsdl"/>
  <binding name="bd_insertarCantidadConsultas_ptt-binding" type="tns:bd_insertarCantidadConsultas_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="bd_insertarCantidadConsultas">
      <soap:operation soapAction="bd_insertarCantidadConsultas"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="bd_insertarCantidadConsultas-service">
    <port name="bd_insertarCantidadConsultas-port" binding="tns:bd_insertarCantidadConsultas_ptt-binding">
      <soap:address location="jca://eis/DB/ITEL_SOA"/>
    </port>
  </service>
</definitions>