<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/ITEL/Adaptadores/bd_paquetesRecurrentes" name="bd_paquetesRecurrentes-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/ITEL/Adaptadores/bd_paquetesRecurrentes" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ITEL/Adaptadores/bd_paquetesRecurrentes" location="../Resources/WSDLs/paquetesRecurrentes_BD.wsdl"/>
  <binding name="bd_paquetesRecurrentes_ptt-binding" type="tns:bd_paquetesRecurrentes_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="bd_paquetesRecurrentes">
      <soap:operation soapAction="bd_paquetesRecurrentes"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="bd_paquetesRecurrentes-service">
    <port name="bd_paquetesRecurrentes-port" binding="tns:bd_paquetesRecurrentes_ptt-binding">
      <soap:address location="jca://eis/DB/ITEL_SOA"/>
    </port>
  </service>
</definitions>