<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/ITEL/Adaptadores/bd_validarUsuarioContrasena" name="bd_validarUsuarioContrasena-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/ITEL/Adaptadores/bd_validarUsuarioContrasena" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ITEL/Adaptadores/bd_validarUsuarioContrasena" location="../Resources/WSDLs/validarUsuarioContrasena_BD.wsdl"/>
  <binding name="bd_validarUsuarioContrasena_ptt-binding" type="tns:bd_validarUsuarioContrasena_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="bd_validarUsuarioContrasena">
      <soap:operation soapAction="bd_validarUsuarioContrasena"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="bd_validarUsuarioContrasena-service">
    <port name="bd_validarUsuarioContrasena-port" binding="tns:bd_validarUsuarioContrasena_ptt-binding">
      <soap:address location="jca://eis/DB/ITEL_SOA"/>
    </port>
  </service>
</definitions>