<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/Ensayo/Reglas/bd_validacionGeneral" name="bd_validacionGeneral-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/Ensayo/Reglas/bd_validacionGeneral" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/Ensayo/Reglas/bd_validacionGeneral" location="../Resources/WSDLs/validacionGeneral_BD.wsdl"/>
  <binding name="bd_validacionGeneral_ptt-binding" type="tns:bd_validacionGeneral_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="bd_validacionGeneral">
      <soap:operation soapAction="bd_validacionGeneral"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="bd_validacionGeneral-service">
    <port name="bd_validacionGeneral-port" binding="tns:bd_validacionGeneral_ptt-binding">
      <soap:address location="jca://eis/DB/ITEL_SOA"/>
    </port>
  </service>
</definitions>