<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/ITEL/Adaptadores/bd_consultarEstadoRecarga" name="bd_consultarEstadoRecarga-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/ITEL/Adaptadores/bd_consultarEstadoRecarga" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ITEL/Adaptadores/bd_consultarEstadoRecarga" location="../Resources/WSDLs/consultarEstadoRecarga_BD.wsdl"/>
  <binding name="bd_consultarEstadoRecarga_ptt-binding" type="tns:bd_consultarEstadoRecarga_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="bd_consultarEstadoRecarga">
      <soap:operation soapAction="bd_consultarEstadoRecarga"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="bd_consultarEstadoRecarga-service">
    <port name="bd_consultarEstadoRecarga-port" binding="tns:bd_consultarEstadoRecarga_ptt-binding">
      <soap:address location="jca://eis/DB/ITEL_SOA"/>
    </port>
  </service>
</definitions>