<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/getCreditExceptions_BS/Project1/getCreditExceptions" name="getCreditExceptions-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/getCreditExceptions_BS/Project1/getCreditExceptions" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/getCreditExceptions_BS/Project1/getCreditExceptions" location="../Resources/WSDLs/getCreditExceptions_BD.wsdl"/>
  <binding name="getCreditExceptions_ptt-binding" type="tns:getCreditExceptions_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="getCreditExceptions">
      <soap:operation soapAction="getCreditExceptions"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="getCreditExceptions-service">
    <port name="getCreditExceptions-port" binding="tns:getCreditExceptions_ptt-binding">
      <soap:address location="jca://eis/DB/Rules_Engine"/>
    </port>
  </service>
</definitions>