<?binding.jca bd_actualizarMinRecargaEsc_db.jca?><wsdl:definitions name="bd_actualizarMinRecargaEsc" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/ITEL/Adaptadores/bd_actualizarMinRecargaEsc" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/SOA_TEST/PKG_SOA_ITEL/PRC_ACTUALIZAR_MIN_RECARGAESC/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/ITEL/Adaptadores/bd_actualizarMinRecargaEsc" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/">
    <plt:partnerLinkType name="bd_actualizarMinRecargaEsc_plt">
        <plt:role name="bd_actualizarMinRecargaEsc_role">
            <plt:portType name="tns:bd_actualizarMinRecargaEsc_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/SOA_TEST/PKG_SOA_ITEL/PRC_ACTUALIZAR_MIN_RECARGAESC/" schemaLocation="../Schemas/BD_ITEL_ACTUALIZARMINRECARGAESC.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="args_in_msg">
        <wsdl:part name="InputParameters" element="db:InputParameters"/>
    </wsdl:message>
    <wsdl:portType name="bd_actualizarMinRecargaEsc_ptt">
        <wsdl:operation name="bd_actualizarMinRecargaEsc">
            <wsdl:input message="tns:args_in_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>