<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/jms/Comcel/ITEL/consumirAuditoriaRecargaSATJMS" name="consumirAuditoriaRecargaSATJMS-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/jms/Comcel/ITEL/consumirAuditoriaRecargaSATJMS" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/jms/Comcel/ITEL/consumirAuditoriaRecargaSATJMS" location="consumirAuditoriaRecargaSATJMS.wsdl"/>
  <binding name="consumirAuditoriaRecargaSAT_ptt-binding" type="tns:consumirAuditoriaRecargaSAT_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="consumirAuditoriaRecargaSAT">
      <soap:operation soapAction="consumirAuditoriaRecargaSAT"/>
      <input>
        <soap:body use="literal"/>
      </input>
    </operation>
  </binding>
  <service name="consumirAuditoriaRecargaSATJMS-service">
    <port name="consumirAuditoriaRecargaSATJMS-port" binding="tns:consumirAuditoriaRecargaSAT_ptt-binding">
      <soap:address location="jca://eis/wls/Queue"/>
    </port>
  </service>
</definitions>