<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/jms/Comcel/ITEL/consumirAuditoriaRecargaRARJMS" name="consumirAuditoriaRecargaRARJMS-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/jms/Comcel/ITEL/consumirAuditoriaRecargaRARJMS" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/jms/Comcel/ITEL/consumirAuditoriaRecargaRARJMS" location="consumirAuditoriaRecargaRARJMS.wsdl"/>
  <binding name="consumirAuditoriaRecargaRAR_ptt-binding" type="tns:consumirAuditoriaRecargaRAR_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="consumirAuditoriaRecargaRAR">
      <soap:operation soapAction="consumirAuditoriaRecargaRAR"/>
      <input>
        <soap:body use="literal"/>
      </input>
    </operation>
  </binding>
  <service name="consumirAuditoriaRecargaRARJMS-service">
    <port name="consumirAuditoriaRecargaRARJMS-port" binding="tns:consumirAuditoriaRecargaRAR_ptt-binding">
      <soap:address location="jca://eis/wls/Queue"/>
    </port>
  </service>
</definitions>