<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/jms/Comcel/ITEL/consumirNotificacionSMSJMS" name="consumirNotificacionSMSJMS-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/jms/Comcel/ITEL/consumirNotificacionSMSJMS" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/jms/Comcel/ITEL/consumirNotificacionSMSJMS" location="consumirNotificacionSMSJMS.wsdl"/>
  <binding name="consumirNotificacionSMS_ptt-binding" type="tns:consumirNotificacionSMS_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="consumirNotificacionSMS">
      <soap:operation soapAction="consumirNotificacionSMS"/>
      <input>
        <soap:body use="literal"/>
      </input>
    </operation>
  </binding>
  <service name="consumirNotificacionSMSJMS-service">
    <port name="consumirNotificacionSMSJMS-port" binding="tns:consumirNotificacionSMS_ptt-binding">
      <soap:address location="jca://eis/wls/Queue"/>
    </port>
  </service>
</definitions>