<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/jms/Comcel/ITEL/consumirAuditoriaPromoPaquetesTATJMS" name="consumirAuditoriaPromoPaquetesTATJMS-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/jms/Comcel/ITEL/consumirAuditoriaPromoPaquetesTATJMS" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/jms/Comcel/ITEL/consumirAuditoriaPromoPaquetesTATJMS" location="consumirAuditoriaPromoPaquetesTATJMS.wsdl"/>
  <binding name="consumirAuditoriaPromoPaquetesTAT_ptt-binding" type="tns:consumirAuditoriaPromoPaquetesTAT_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="consumirAuditoriaPromoPaquetesTAT">
      <soap:operation soapAction="consumirAuditoriaPromoPaquetesTAT"/>
      <input>
        <soap:body use="literal"/>
      </input>
    </operation>
  </binding>
  <service name="consumirAuditoriaPromoPaquetesTATJMS-service">
    <port name="consumirAuditoriaPromoPaquetesTATJMS-port" binding="tns:consumirAuditoriaPromoPaquetesTAT_ptt-binding">
      <soap:address location="jca://eis/wls/Queue"/>
    </port>
  </service>
</definitions>