<wsdl:definitions name="ConsultarContractTemp_Contract" targetNamespace="http://www.comcel.com.co/ConsultarContractTemp_Contract/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://www.comcel.com.co/ConsultarContractTemp_Contract/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<wsdl:types>
			<schema xmlns="http://www.w3.org/2001/XMLSchema">
				<import namespace="http://www.comcel.com.co/ConsultarContractTemp_Contract/" schemaLocation="../Schemas/PS_ITEL_CONSULTARCONTRACTTEMP_CONTRACT.xsd"/>
			</schema>
	</wsdl:types>
	<wsdl:message name="Input_Parameters">
		<wsdl:part element="tns:Input_Parameters" name="Input_Parameters"/>
	</wsdl:message>
	<wsdl:message name="WS_Result">
		<wsdl:part element="tns:WS_Result" name="WS_Result"/>
	</wsdl:message>
	<wsdl:portType name="ConsultarContractTemp_Contract">
		<wsdl:operation name="consultarContractTemp_Contract">
			<wsdl:input message="tns:Input_Parameters"/>
			<wsdl:output message="tns:WS_Result"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="ConsultarContractTemp_ContractSOAP" type="tns:ConsultarContractTemp_Contract">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="consultarContractTemp_Contract">
			<soap:operation soapAction="http://www.comcel.com.co/ConsultarContractTemp_Contract/consultarContractTemp_Contract"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="ConsultarContractTemp_Contract">
		<wsdl:port binding="tns:ConsultarContractTemp_ContractSOAP" name="ConsultarContractTemp_ContractSOAP">
			<soap:address location="http://www.comcel.com.co/"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>