<?binding.jca db_consultarPlataformaOffer_db.jca?>
<wsdl:definitions name="db_consultarPlataformaOffer"
	targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/ITEL/Adaptadores/db_consultarPlataformaOffer"
	xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/sp/db_consultarPlataformaOffer"
	xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/ITEL/Adaptadores/db_consultarPlataformaOffer"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/">
	<plt:partnerLinkType name="db_consultarPlataformaOffer_plt">
		<plt:role name="db_consultarPlataformaOffer_role">
			<plt:portType name="tns:db_consultarPlataformaOffer_ptt" />
		</plt:role>
	</plt:partnerLinkType>
	<wsdl:types>
		<schema xmlns="http://www.w3.org/2001/XMLSchema">
			<import
				namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/db_consultarPlataformaOffer"
				schemaLocation="../Schemas/BD_CONSULTAR_PLATAFORMA_OFFER.xsd" />
		</schema>
	</wsdl:types>
	<wsdl:message name="args_in_msg">
		<wsdl:part name="InputParameters" element="db:InputParameters" />
	</wsdl:message>
	<wsdl:message name="args_out_msg">
		<wsdl:part name="OutputParameters" element="db:OutputParameters" />
	</wsdl:message>
	<wsdl:portType name="db_consultarPlataformaOffer_ptt">
		<wsdl:operation name="db_consultarPlataformaOffer">
			<wsdl:input message="tns:args_in_msg" />
			<wsdl:output message="tns:args_out_msg" />
		</wsdl:operation>
	</wsdl:portType>
</wsdl:definitions>