<wsdl:definitions name="consumirAuditoriaDiaSorpresaElegidosJMS" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/jms/Comcel/ITEL/consumirAuditoriaDiaSorpresaElegidosJMS" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/jms/Comcel/ITEL/consumirAuditoriaDiaSorpresaElegidosJMS" xmlns:pc="http://xmlns.oracle.com/pcbpel/" xmlns:imp1="http://www.comcel.com.co/AuditoriaDiaSorpresaElegidosITEL/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/">
	<plt:partnerLinkType name="consumirAuditoriaDiaSorpresaElegidos_plt">
		<plt:role name="consumirAuditoriaDiaSorpresaElegidos_role">
			<plt:portType name="tns:consumirAuditoriaDiaSorpresaElegidos_ptt"/>
		</plt:role>
	</plt:partnerLinkType>
	<wsdl:types>
		<schema xmlns="http://www.w3.org/2001/XMLSchema">
			<import namespace="http://www.comcel.com.co/AuditoriaDiaSorpresaElegidosITEL/" schemaLocation="../Schemas/MS_ITEL_AUDITORIADIASORPRESAELEGIDOS.xsd"/>
		</schema>
	</wsdl:types>
	<wsdl:message name="consumirAuditoriaDiaSorpresaElegidos_msg">
		<wsdl:part name="body" element="imp1:Input_Parameters"/>
	</wsdl:message>
	<wsdl:portType name="consumirAuditoriaDiaSorpresaElegidos_ptt">
		<wsdl:operation name="consumirAuditoriaDiaSorpresaElegidos">
			<wsdl:input message="tns:consumirAuditoriaDiaSorpresaElegidos_msg"/>
		</wsdl:operation>
	</wsdl:portType>
</wsdl:definitions>