<wsdl:definitions name="EnviarSMS" targetNamespace="http://www.comcel.com.co/EnviarSMS/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://www.comcel.com.co/EnviarSMS/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<wsdl:types>
			<schema xmlns="http://www.w3.org/2001/XMLSchema">
				<import namespace="http://www.comcel.com.co/EnviarSMS/" schemaLocation="../Schemas/PS_ITEL_ENVIARSMS.xsd"/>
			</schema>
	</wsdl:types>
	<wsdl:message name="Input_Parameters">
		<wsdl:part element="tns:Input_Parameters" name="Input_Parameters"/>
	</wsdl:message>
	
	<wsdl:portType name="EnviarSMS">
		<wsdl:operation name="enviarSMS">
			<wsdl:input message="tns:Input_Parameters"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="EnviarSMSSOAP" type="tns:EnviarSMS">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="enviarSMS">
			<soap:operation soapAction="http://www.comcel.com.co/EnviarSMS/enviarSMS"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="EnviarSMS">
		<wsdl:port binding="tns:EnviarSMSSOAP" name="EnviarSMSSOAP">
			<soap:address location="http://www.comcel.com.co/"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>