<wsdl:definitions name="enviarNotificacionSMSJMS" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/jms/Comcel/ITEL/enviarNotificacionSMSJMS" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/jms/Comcel/ITEL/enviarNotificacionSMSJMS" xmlns:imp1="http://www.comcel.com.co/NotificacionSMSITEL/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/">
	<plt:partnerLinkType name="enviarNotificacionSMS_plt">
		<plt:role name="enviarNotificacionSMS_role">
			<plt:portType name="tns:enviarNotificacionSMS_ptt"/>
		</plt:role>
	</plt:partnerLinkType>
	<wsdl:types>
		<schema xmlns="http://www.w3.org/2001/XMLSchema">
			<import namespace="http://www.comcel.com.co/NotificacionSMSITEL/" schemaLocation="../Schemas/MS_ITEL_NOTIFICACION_SMS.xsd"/>
		</schema>
	</wsdl:types>
	<wsdl:message name="enviarNotificacionSMS_msg">
		<wsdl:part name="body" element="imp1:Input_Parameters"/>
	</wsdl:message>
	<wsdl:portType name="enviarNotificacionSMS_ptt">
		<wsdl:operation name="enviarNotificacionSMS">
			<wsdl:input message="tns:enviarNotificacionSMS_msg"/>
		</wsdl:operation>
	</wsdl:portType>
</wsdl:definitions>