<?binding.jca db_insertarConsecutivo_db.jca?><wsdl:definitions name="insertarConsecutivo" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/Application1/conecel/insertarConsecutivo" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/ITELSOA/PKG_SOA_ITEL/PRC_INSERTAR_CONSECUTIVO/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/Application1/conecel/insertarConsecutivo" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/">
    <plt:partnerLinkType name="insertarConsecutivo_plt">
        <plt:role name="insertarConsecutivo_role">
            <plt:portType name="tns:insertarConsecutivo_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ITELSOA/PKG_SOA_ITEL/PRC_INSERTAR_CONSECUTIVO/" schemaLocation="../Schemas/BD_ITEL_INSERTAR_CONSECUTIVO.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="args_in_msg">
        <wsdl:part name="InputParameters" element="db:InputParameters"/>
    </wsdl:message>
    <wsdl:message name="args_out_msg">
        <wsdl:part name="OutputParameters" element="db:OutputParameters"/>
    </wsdl:message>
    <wsdl:portType name="insertarConsecutivo_ptt">
        <wsdl:operation name="insertarConsecutivo">
            <wsdl:input message="tns:args_in_msg"/>
            <wsdl:output message="tns:args_out_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>