<wsdl:definitions name="insertarCantidadConsultas_PS" targetNamespace="http://www.comcel.com.co/insertarCantidadConsultas_PS/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://www.comcel.com.co/insertarCantidadConsultas_PS/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsd1="http://www.comcel.com.co/InsertarCantidadConsultasDia/">
	<wsdl:types>
		<xsd:schema>
			<xsd:import namespace="http://www.comcel.com.co/InsertarCantidadConsultasDia/" schemaLocation="../Schemas/PS_ITEL_INSERTARCANTIDADCONSULTASDIA.xsd">
			</xsd:import>
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="insertarCantidadConsultasRequest">
		<wsdl:part element="xsd1:Input_Parameters" name="parameters"/>
	</wsdl:message>
	<wsdl:message name="insertarCantidadConsultasResponse">
		<wsdl:part element="xsd1:WS_Result" name="parameters"/>
	</wsdl:message>
	<wsdl:portType name="insertarCantidadConsultas_PS">
		<wsdl:operation name="insertarCantidadConsultas">
			<wsdl:input message="tns:insertarCantidadConsultasRequest"/>
			<wsdl:output message="tns:insertarCantidadConsultasResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="insertarCantidadConsultas_PSSOAP" type="tns:insertarCantidadConsultas_PS">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="insertarCantidadConsultas">
			<soap:operation soapAction="http://www.comcel.com.co/insertarCantidadConsultas_PS/insertarCantidadConsultas"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="insertarCantidadConsultas_PS">
		<wsdl:port binding="tns:insertarCantidadConsultas_PSSOAP" name="insertarCantidadConsultas_PSSOAP">
			<soap:address location="http://www.comcel.com.co"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>