<wsdl:definitions name="insertarAuditoriaBloqueo_PS" targetNamespace="http://www.comcel.com.co/insertarAuditoriaBloqueo_PS/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://www.comcel.com.co/insertarAuditoriaBloqueo_PS/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsd1="http://www.comcel.com.co/InsertarAuditoriaBloqueo">
	<wsdl:types>
		<xsd:schema>
			<xsd:import namespace="http://www.comcel.com.co/InsertarAuditoriaBloqueo" schemaLocation="../Schemas/PS_ITEL_INSERTARAUDITORIABLOQUEO.xsd">
			</xsd:import>
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="insertarAuditoriaBloqueoRequest">
		<wsdl:part element="xsd1:Input_Parameters" name="Input_Parameters"/>
	</wsdl:message>
	<wsdl:message name="insertarAuditoriaBloqueoResponse">
		<wsdl:part element="xsd1:WS_Result" name="WS_Result"/>
	</wsdl:message>
	<wsdl:portType name="insertarAuditoriaBloqueo_PS">
		<wsdl:operation name="insertarAuditoriaBloqueo">
			<wsdl:input message="tns:insertarAuditoriaBloqueoRequest"/>
			<wsdl:output message="tns:insertarAuditoriaBloqueoResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="insertarAuditoriaBloqueo_PSSOAP" type="tns:insertarAuditoriaBloqueo_PS">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="insertarAuditoriaBloqueo">
			<soap:operation soapAction="http://www.comcel.com.co/insertarAuditoriaBloqueo_PS/insertarAuditoriaBloqueo"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="insertarAuditoriaBloqueo_PS">
		<wsdl:port binding="tns:insertarAuditoriaBloqueo_PSSOAP" name="insertarAuditoriaBloqueo_PSSOAP">
			<soap:address location="http://www.comcel.com.co/"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>