<wsdl:definitions name="insertarElegidoFijo_PS" targetNamespace="http://www.comcel.com.co/insertarElegidoFijo_PS/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://www.comcel.com.co/insertarElegidoFijo_PS/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsd1="http://www.comcel.com.co/PS_INSERTAR_ELEGIDO_ILIMITADO_FIJO">
	<wsdl:types>
		<xsd:schema>
			<xsd:import namespace="http://www.comcel.com.co/PS_INSERTAR_ELEGIDO_ILIMITADO_FIJO" schemaLocation="../Schemas/PS_ITEL_INSERTAR_ELEGIDO_ILIMITADO_FIJO.xsd">
			</xsd:import>
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="insertarElegidoFijoRequest">
		<wsdl:part element="xsd1:Input_Parameters" name="parameters"/>
	</wsdl:message>
	<wsdl:message name="insertarElegidoFijoResponse">
		<wsdl:part element="xsd1:WS_Result" name="parameters"/>
	</wsdl:message>
	<wsdl:portType name="insertarElegidoFijo_PS">
		<wsdl:operation name="insertarElegidoFijo">
			<wsdl:input message="tns:insertarElegidoFijoRequest"/>
			<wsdl:output message="tns:insertarElegidoFijoResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="insertarElegidoFijo_PSSOAP" type="tns:insertarElegidoFijo_PS">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="insertarElegidoFijo">
			<soap:operation soapAction="http://www.comcel.com.co/insertarElegidoFijo_PS/insertarElegidoFijo"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="insertarElegidoFijo_PS">
		<wsdl:port binding="tns:insertarElegidoFijo_PSSOAP" name="insertarElegidoFijo_PSSOAP">
			<soap:address location="http://www.comcel.com.co"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>