<wsdl:definitions name="insertarAuditoriaDiaSorpresaRecarga" targetNamespace="http://www.comcel.com.co/insertarAuditoriaDiaSorpresaRecarga/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://www.comcel.com.co/insertarAuditoriaDiaSorpresaRecarga/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsd1="http://www.comcel.com.co/InsertarAuditoriaDiaSorpresaRecarga">
	<wsdl:types>
		<xsd:schema>
			<xsd:import namespace="http://www.comcel.com.co/InsertarAuditoriaDiaSorpresaRecarga" schemaLocation="../Schemas/PS_ITEL_INSERTAR_AUDITORIADIASORPRESARECARGA.xsd">
			</xsd:import>
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="insertarElegidoRequest">
		<wsdl:part element="xsd1:Input_Parameters" name="parameters"/>
	</wsdl:message>
	<wsdl:message name="insertarElegidoResponse">
		<wsdl:part element="xsd1:WS_Result" name="parameters"/>
	</wsdl:message>
	<wsdl:portType name="insertarAuditoriaDiaSorpresaRecarga">
		<wsdl:operation name="insertarElegido">
			<wsdl:input message="tns:insertarElegidoRequest"/>
			<wsdl:output message="tns:insertarElegidoResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="insertarAuditoriaDiaSorpresaRecargaSOAP" type="tns:insertarAuditoriaDiaSorpresaRecarga">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="insertarElegido">
			<soap:operation soapAction="http://www.comcel.com.co/insertarAuditoriaDiaSorpresaRecarga/insertarElegido"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="insertarAuditoriaDiaSorpresaRecarga">
		<wsdl:port binding="tns:insertarAuditoriaDiaSorpresaRecargaSOAP" name="insertarAuditoriaDiaSorpresaRecargaSOAP">
			<soap:address location="http://www.comcel.com.co"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>