<wsdl:definitions name="consumirAuditoriaJMS" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/jms/Comcel/ITEL/consumirAuditoriaJMS" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/jms/Comcel/ITEL/consumirAuditoriaJMS" xmlns:pc="http://xmlns.oracle.com/pcbpel/" xmlns:imp1="http://www.comcel.com.co/AuditoriaITEL/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/">
	<plt:partnerLinkType name="consumirAuditoria_plt">
		<plt:role name="consumirAuditoria_role">
			<plt:portType name="tns:consumirAuditoria_ptt"/>
		</plt:role>
	</plt:partnerLinkType>
	<wsdl:types>
		<schema xmlns="http://www.w3.org/2001/XMLSchema">
			<import namespace="http://www.comcel.com.co/AuditoriaITEL/" schemaLocation="../Schemas/PS_ITEL_AUDITORIA.xsd"/>
		</schema>
	</wsdl:types>
	<wsdl:message name="consumirAuditoria_msg">
		<wsdl:part name="body" element="imp1:Input_Parameters"/>
	</wsdl:message>
	<wsdl:portType name="consumirAuditoria_ptt">
		<wsdl:operation name="consumirAuditoria">
			<wsdl:input message="tns:consumirAuditoria_msg"/>
		</wsdl:operation>
	</wsdl:portType>
</wsdl:definitions>