<wsdl:definitions name="enviarAuditoriaDiaSorpresaRecargaJMS" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/jms/Comcel/ITEL/enviarAuditoriaDiaSorpresaRecargaJMS" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/jms/Comcel/ITEL/enviarAuditoriaDiaSorpresaRecargaJMS" xmlns:imp1="http://www.comcel.com.co/AuditoriaITEL/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/">
	<plt:partnerLinkType name="enviarAuditoriaDiaSorpresaRecarga_plt">
		<plt:role name="enviarAuditoriaDiaSorpresaRecarga_role">
			<plt:portType name="tns:enviarAuditoriaDiaSorpresaRecarga_ptt"/>
		</plt:role>
	</plt:partnerLinkType>
	<wsdl:types>
		<schema xmlns="http://www.w3.org/2001/XMLSchema">
			<import namespace="http://www.comcel.com.co/AuditoriaITEL/" schemaLocation="../Schemas/MS_ITEL_AUDITORIADIASORPRESARECARGA.xsd"/>
		</schema>
	</wsdl:types>
	<wsdl:message name="enviarAuditoriaDiaSorpresaRecarga_msg">
		<wsdl:part name="body" element="imp1:Input_Parameters"/>
	</wsdl:message>
	<wsdl:portType name="enviarAuditoriaDiaSorpresaRecarga_ptt">
		<wsdl:operation name="enviarAuditoriaDiaSorpresaRecarga">
			<wsdl:input message="tns:enviarAuditoriaDiaSorpresaRecarga_msg"/>
		</wsdl:operation>
	</wsdl:portType>
</wsdl:definitions>