<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/Ensayo/Reglas/bd_compensarElegidoSMS" name="bd_compensarElegidoSMS-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/Ensayo/Reglas/bd_compensarElegidoSMS" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/Ensayo/Reglas/bd_compensarElegidoSMS" location="../Resources/WSDLs/compensarElegidoSMS_BD.wsdl"/>
  <binding name="bd_compensarElegidoSMS_ptt-binding" type="tns:bd_compensarElegidoSMS_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="bd_compensarElegidoSMS">
      <soap:operation soapAction="bd_compensarElegidoSMS"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="bd_compensarElegidoSMS-service">
    <port name="bd_compensarElegidoSMS-port" binding="tns:bd_compensarElegidoSMS_ptt-binding">
      <soap:address location="jca://eis/DB/ITEL_SOA"/>
    </port>
  </service>
</definitions>