<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/jms/Comcel/ITEL/enviarCompensacionJMS" name="enviarCompensacionJMS-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/jms/Comcel/ITEL/enviarCompensacionJMS" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/jms/Comcel/ITEL/enviarCompensacionJMS" location="../Resources/WSDLs/enviarCompensacionJMS.wsdl"/>
  <binding name="enviarCompensacion_ptt-binding" type="tns:enviarCompensacion_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="enviarCompensacion">
      <soap:operation soapAction="enviarCompensacion"/>
      <input>
        <soap:body use="literal"/>
      </input>
    </operation>
  </binding>
  <service name="enviarCompensacionJMS-service">
    <port name="enviarCompensacionJMS-port" binding="tns:enviarCompensacion_ptt-binding">
      <soap:address location="jca://eis/wls/Queue"/>
    </port>
  </service>
</definitions>