<wsdl:definitions name="CompensarElegidoIlimitado" targetNamespace="http://www.comcel.com.co/CompensarElegidoIlimitado/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://www.comcel.com.co/CompensarElegidoIlimitado/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<wsdl:types>
		<schema xmlns="http://www.w3.org/2001/XMLSchema">
			<import namespace="http://www.comcel.com.co/CompensarElegidoIlimitado/" schemaLocation="../Schemas/PS_ITEL_COMPENSAR_ELEGIDOILIMITADO.xsd"/>
		</schema>
	</wsdl:types>
	<wsdl:message name="Input_Parameters">
		<wsdl:part element="tns:Input_Parameters" name="Input_Parameters"/>
	</wsdl:message>
	<wsdl:message name="WS_Result">
	</wsdl:message>
	<wsdl:portType name="CompensarElegidoIlimitado">
		<wsdl:operation name="compensarElegidoIlimitado">
			<wsdl:input message="tns:Input_Parameters"/>
			<wsdl:output message="tns:WS_Result"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="CompensarElegidoIlimitadoSOAP" type="tns:CompensarElegidoIlimitado">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="compensarElegidoIlimitado">
			<soap:operation soapAction="http://www.comcel.com.co/CompensarElegidoIlimitado/compensarElegidoIlimitado"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="CompensarElegidoIlimitado">
		<wsdl:port binding="tns:CompensarElegidoIlimitadoSOAP" name="CompensarElegidoIlimitadoSOAP">
			<soap:address location="http://www.comcel.com.co/"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>