<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/jms/Comcel/ITEL/consumirCompensacionJMS" name="consumirCompensacionJMS-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/jms/Comcel/ITEL/consumirCompensacionJMS" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/jms/Comcel/ITEL/consumirCompensacionJMS" location="consumirCompensacionJMS.wsdl"/>
  <binding name="consumirCompensacion_ptt-binding" type="tns:consumirCompensacion_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="consumirCompensacion">
      <soap:operation soapAction="consumirCompensacion"/>
      <input>
        <soap:body use="literal"/>
      </input>
    </operation>
  </binding>
  <service name="consumirCompensacionJMS-service">
    <port name="consumirCompensacionJMS-port" binding="tns:consumirCompensacion_ptt-binding">
      <soap:address location="jca://eis/wls/Queue"/>
    </port>
  </service>
</definitions>