<wsdl:definitions name="enviarCompensacionJMS" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/jms/Comcel/ITEL/enviarCompensacionJMS" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/jms/Comcel/ITEL/enviarCompensacionJMS" xmlns:imp1="http://www.comcel.com.co/CompensacionITEL/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/">
	<plt:partnerLinkType name="enviarCompensacion_plt">
		<plt:role name="enviarCompensacion_role">
			<plt:portType name="tns:enviarCompensacion_ptt"/>
		</plt:role>
	</plt:partnerLinkType>
	<wsdl:types>
		<schema xmlns="http://www.w3.org/2001/XMLSchema">
			<import namespace="http://www.comcel.com.co/CompensacionITEL/" schemaLocation="../Schemas/PS_ITEL_COMPENSACION.xsd"/>
		</schema>
	</wsdl:types>
	<wsdl:message name="enviarCompensacion_msg">
		<wsdl:part name="body" element="imp1:Input_Parameters"/>
	</wsdl:message>
	<wsdl:portType name="enviarCompensacion_ptt">
		<wsdl:operation name="enviarCompensacion">
			<wsdl:input message="tns:enviarCompensacion_msg"/>
		</wsdl:operation>
	</wsdl:portType>
</wsdl:definitions>