<wsdl:definitions name="ActualizarFechaExpiracionPaqueteOCS" targetNamespace="http://www.comcel.com.co/ActualizarFechaExpiracionPaqueteOCS/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://www.comcel.com.co/ActualizarFechaExpiracionPaqueteOCS/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<wsdl:types>
		<schema xmlns="http://www.w3.org/2001/XMLSchema">
			<import namespace="http://www.comcel.com.co/ActualizarFechaExpiracionPaqueteOCS/" schemaLocation="../Schemas/PS_ITEL_ACTUALIZAR_FECHA_EXPIRACION.xsd"/>
		</schema>
	</wsdl:types>
	<wsdl:message name="Input_Parameters">
		<wsdl:part element="tns:Input_Parameters" name="Input_Parameters"/>
	</wsdl:message>
	<wsdl:message name="WS_Result">
		<wsdl:part element="tns:WS_Result" name="WS_Result"/>
	</wsdl:message>
	<wsdl:portType name="ActualizarFechaExpiracionPaqueteOCS">
		<wsdl:operation name="actualizarFechaExpiracionPaqueteOCS">
			<wsdl:input message="tns:Input_Parameters"/>
			<wsdl:output message="tns:WS_Result"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="ActualizarFechaExpiracionPaqueteOCSSOAP" type="tns:ActualizarFechaExpiracionPaqueteOCS">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="actualizarFechaExpiracionPaqueteOCS">
			<soap:operation soapAction="http://www.comcel.com.co/ActualizarFechaExpiracionPaqueteOCS/actualizarFechaExpiracionPaqueteOCS"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="ActualizarFechaExpiracionPaqueteOCS">
		<wsdl:port binding="tns:ActualizarFechaExpiracionPaqueteOCSSOAP" name="ActualizarFechaExpiracionPaqueteOCSSOAP">
			<soap:address location="http://www.comcel.com.co/"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>